table 'Key Measures'
	lineageTag: 2ffd62a2-97f3-4d3c-b5f3-89b0afd4fc53

	measure 'Total Sales' = SUM ( Sales[Total Revenue] )
		formatString: \$#,0.00;-\$#,0.00;\$#,0.00
		lineageTag: ade1eecd-9d1a-426c-afef-79970f377a0b

		annotation PBI_FormatHint = {"currencyCulture":"en-NZ"}

	measure 'Total Costs' = ```
			
			SUMX ( Sales , 
				Sales[Order Quantity] * Sales[Total Unit Cost] )
			```
		formatString: \$#,0.00;-\$#,0.00;\$#,0.00
		lineageTag: 9e13b158-f982-4f3e-a27e-f6fbdb25ffec

		annotation PBI_FormatHint = {"currencyCulture":"en-NZ"}

	measure 'Total Profits' = [Total Sales] - [Total Costs]
		formatString: \$#,0.00;-\$#,0.00;\$#,0.00
		lineageTag: bec47463-fd14-4975-b81e-88cdd7e7e9de

		annotation PBI_FormatHint = {"currencyCulture":"en-NZ"}

	measure 'Total Transactions' =
			
			COUNTROWS ( Sales )
		formatString: #,0
		lineageTag: aeed2593-75a7-4761-af88-9daa4824fed3

	measure 'Total Items' = SUM ( Sales[Order Quantity] )
		formatString: #,0
		lineageTag: 6301a3f0-f16f-4116-9808-77892319e047

	measure 'Profit Margin' =
			
			DIVIDE( [Total Profits] , [Total Sales] , 0 )
		formatString: #,0\ %;-#,0\ %;#,0\ %
		lineageTag: 66478d22-8fed-4601-8e65-cae350129a10

	measure 'Last Sale Amount' =
			
			CALCULATE( [Total Sales] , LASTNONBLANK( Dates[Date] , [Total Sales] ) )
		formatString: \$#,0.00;-\$#,0.00;\$#,0.00
		lineageTag: cab9459c-76bf-4999-a99d-916bb32c5ee9

		annotation PBI_FormatHint = {"currencyCulture":"en-NZ"}

	measure 'Last Sales Date' = LASTNONBLANK( Dates[Date] , [Total Sales] )
		formatString: Short Date
		lineageTag: 85051c58-07b0-42b5-a27d-a47f5ae10a51

	measure 'Total Customers' =
			
			DISTINCTCOUNT( Customers[Customer Names] )
		formatString: 0
		lineageTag: 1e2e3dae-721a-4816-afde-c0ac3bbe82ea

	measure 'Total Products' = DISTINCTCOUNT( Products[Product Name] )
		formatString: 0
		lineageTag: 71fabf53-e94f-4377-a4e7-a8f32d2e3f14

	measure 'Total Countries' = DISTINCTCOUNT( Regions[City] )
		formatString: 0
		lineageTag: 6bcdfbf9-69e7-4436-bf97-642cb211dcb6

	measure 'Total Customers with Regions' = ```
			
			CALCULATE( 
				[Total Customers],
					Sales)
			//Used to work out how many customers sold to within each regions
			```
		formatString: 0
		lineageTag: 6fc766a6-68e5-453f-a484-bd3536f50c0b

	measure 'Total Products with Regions' = ```
			
			CALCULATE( 
				[Total Products],
					Sales)
			//Used to work out how many customers sold to within each regions
			```
		formatString: 0
		lineageTag: e2c2a30b-c8c4-47d0-a96d-293c6ef8b373

	measure 'Total Countries w/Sales' = ```
			
			CALCULATE( 
				[Total Countries],
					Sales)
			//counts disctinct countries with sales when say a client or product is selected
			```
		formatString: 0
		lineageTag: d0213503-32d4-4570-aa6c-1620d3205b34

	partition 'Key Measures-82de9b22-3090-4991-b173-469268beb908' = m
		mode: import
		queryGroup: 'Measure Groups'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlSKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

