table Products
	lineageTag: 169244df-a4b5-40ec-983a-a58b176da316

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 4d5a6e48-6214-4be3-82b6-a66b7a9043c9
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 54de65a9-1f2d-41fc-a94c-d4231b5f1ed7
		summarizeBy: none
		sourceColumn: Product Name
		sortByColumn: Index

		annotation SummarizationSetBy = Automatic

	partition Products_Data-61e2efaf-7083-4436-bca2-b73142c76c0e = m
		mode: import
		queryGroup: 'Data Model'
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\HAMme\OneDrive - adesso Group\WM Group\00_Initialization\Material\Power BI Workshop Data.xlsx"), null, true),
				    Products_Data_Table = Source{[Item="Products_Data",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Products_Data_Table,{{"Index", Int64.Type}, {"Product Name", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

